---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool-1
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.151-192.168.100.160

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system

