---
- name: Install Oh My ZSH
  become : true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - oh-my-zsh-git

- name: Install Oh My ZSH fzf-tab plugin
  ansible.builtin.git:
    repo: https://github.com/Aloxaf/fzf-tab
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fzf-tab"
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Install Oh My ZSH autosuggestion plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Install Oh My ZSH fast-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/Aloxaf/fast-syntax-highlighting
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting"
  become: true
  become_user: "{{ ansible_user_id }}"
...
