---
- name: Ensure font directory exists
  become: true
  ansible.builtin.file:
    path: /usr/local/share/fonts/otf/ComicCode
    state: directory
    mode: '0755'

- name: Copy Comic Sans OTF fonts to system directory
  become: true
  ansible.builtin.copy:
    src: "fonts/otf/ComicCode/"
    dest: /usr/local/share/fonts/otf/ComicCode/
    mode: '0444'

- name: Update font cache
  become: true
  ansible.builtin.command: fc-cache -f
  changed_when: false
...
