---
# tasks file for lazygit
- name: "Add lazygit copr repo atim/lazygit"
  community.general.copr:
    name: "atim/lazygit"
    state: enabled

- name: "Install lazygit package"
  ansible.builtin.dnf:
    name: lazygit
    state: present
...
