---

- name: Make sure the base packages are installed.
  pacman:
    name:
      - git
      - base-devel
    state: present

- name: Clone the yay repository
  become: true
  become_user: danesh
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    depth: 1

- name: Make and install yay
  become: true
  become_user: danesh
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
