- name: Clone copilot.vim repository
  git:
    repo: 'https://github.com/github/copilot.vim.git'
    dest: '~/.vim/pack/github/start/copilot.vim'
    update: yes

- name: Install Node.js
  become: true
  community.general.pacman:
    name:
    - nodejs
    state: present