---
- name: "Beast - Fedora"
  hosts: localhost
  connection: local
  become: True

  roles:
    - aur_helper
    - zsh

  tasks:
    - name: Install AUR packages
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        use: yay
        name:
          - google-chrome
          - spotify
          - virtualbox-ext-oracle
          - visual-studio-code-bin 
          - google-cloud-cli
          - google-cloud-cli-gke-gcloud-auth-plugin

    - name: Install Arch packages
      become: true
      community.general.pacman:
        name:
          - nerd-fonts
          - k9s
          - virtualbox-host-modules-arch
          - virtualbox-guest-iso
          - virtualbox
          - bluez
          - bluez-utils
          - zsh
          - less
          - tldr
          - man-db
          - minikube
          - fzf
          - the_silver_searcher
          - ripgrep
          - fd
          - kubectl
          - hugo
          - python-crcmod
          - usbutils
          - aspell
          - docker
          - docker-compose
          - vagrant
        state: present
      notify: Start and enable bluetooth

  handlers:
    - name: Start and enable bluetooth
      become: true
      ansible.builtin.systemd:
        name: bluetooth
        state: started
        enabled: yes
...
