---
- name: "Beast - Fedora"
  hosts: localhost
  connection: local
  become: True

  roles:
    - aur_helper

  tasks:
    - name: Install AUR packages
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        use: yay
        name:
          - google-chrome
          - spotify
          - virtualbox-ext-oracle
          - visual-studio-code-bin 

    - name: Install Arch packages
      become: true
      community.general.pacman:
        name:
          - nerd-fonts
          - virtualbox-host-modules-arch
          - virtualbox-guest-iso
          - virtualbox
          - bluez
          - bluez-utils
        state: present
      notify: Start and enable bluetooth

  handlers:
    - name: Start and enable bluetooth
      become: true
      ansible.builtin.systemd:
        name: bluetooth
        state: started
        enabled: yes
...
