---
- name: "Beast - Fedora"
  hosts: localhost
  connection: local
  become: True

  roles:
    - lazygit
    - ssh-keys

      #  tasks:
      #    - name: Test
      #      shell: "uptime"
      #      register: output
      #
      #    - debug: var=output.stdout_lines
...
