---
- name: "r2d2 - Arch Linux"
  hosts: localhost
  connection: local
  become: True

  roles:
    - aur_helper
    - zsh

  tasks:
    - name: Install Arch packages
      become: true
      community.general.pacman:
        name:
          - inetutils
          - nerd-fonts
          - k9s
          - virtualbox-host-modules-arch
          - virtualbox-guest-iso
          - virtualbox
          - bluedevil
          - bluez
          - bluez-utils
          - zsh
          - less
          - tldr
          #- man-db
          - minikube
          - fzf
          #- the_silver_searcher
          #- ripgrep
          #- fd
          #- kubectl
          #- hugo
          #- python-crcmod
          #- usbutils
          #- aspell
          #- docker
          #- docker-compose
          #- vagrant
          #- borg
          #- ncdu
          #- kustomize
          #- argocd
          #- helm
          #- tmux
          - lazygit
          - ghostty
          - btop
          #- kitty
          #- partitionmanager
          #- dosfstools
          #- exfat-utils
          #- ntfs-3g
          #- firefox
        state: present
      notify: Start and enable bluetooth

    - name: Install AUR packages
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        use: yay
        name:
          - google-chrome-beta
          - spotify
          - virtualbox-ext-oracle
          - visual-studio-code-bin 
          - kind
          #- google-cloud-cli
          #- google-cloud-cli-gke-gcloud-auth-plugin
  handlers:
    - name: Start and enable bluetooth
      become: true
      ansible.builtin.systemd:
        name: bluetooth
        state: started
        enabled: yes
...
