---

# Simple playbook that echos hello and prompts for a response.
- name: "Say Hello"
  gather_facts: False
  hosts: localhost
  connection: local
  tasks:

# Ask yes/no question.
  - name: "Pause to get input"
    ansible.builtin.pause:
      prompt: "Are you sure? yes/no?"
      echo: yes
    register: var_yesno

# Get hostname.
  - name: "Get hostname"
    ansible.builtin.setup:
      filter: ansible_hostname

# Echo message is reply is yes.
  - debug:
      msg: "hello from {{ ansible_hostname }}"
    when: var_yesno.user_input | bool